# -*- coding: utf-8 -*-
"""mapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xcAbM3MSU7n-c-skdRo_aw1NCYG_dlUy
"""

#!/usr/bin/env python
"""mapper.py"""
import io 
import re
import sys
import nltk
from nltk.corpus import stopwords
input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='latin1')
nltk.download('stopwords',quiet=True)
# input comes from STDIN (standard input)
for line in input_stream:
    line = line.strip() #removes whitespace
    line = re.sub('[^a-zA-Z]', ' ', line) #non alphabets are changed with whitespace
    words = line.split()# split the line into words
    # increase counters
    for word in words:
        # write the results to STDOUT (standard output);
        # what we output here will be the input for the
        # Reduce step, i.e. the input for reducer.py
        #
        # tab-delimited; the trivial word count is 1
        if word not in stopwords.words('english'):
          print ('%s\t%s' % (word, 1))