# -*- coding: utf-8 -*-
"""mapper_reducer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VNV_KBMH_p0JIdUIMyAppfvGsi2BTpVp
"""

!wget http://qwone.com/~jason/20Newsgroups/20news-18828.tar.gz

!tar -xzvf 20news-18828.tar.gz

!mkdir ~/input1

!cp /content/20news-18828/*/* ~/input1

!cat /content/20news-18828/*/* | python mapper.py | sort | python reducer_py.py