# -*- coding: utf-8 -*-
"""reducer.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q_DfXIvXeN_C6mURi1DdGwy9Ddjc4hkL
"""

from operator import itemgetter
import sys
import io

current_word = None
current_count = 0
word = None
input_stream = io.TextIOWrapper(sys.stdin.buffer, encoding='latin1')
# input comes from STDIN
for line in input_stream:
    # remove leading and trailing whitespace
    line = line.strip()

    # parse the input we got from mapper.py
    word, count = line.split('\t', 1)

    # convert count (currently a string) to int
    try:
        count = int(count)
    except ValueError:
        # count was not a number, so silently
        # ignore/discard this line
        continue

    # this IF-switch only works because Hadoop sorts map output
    # by key (here: word) before it is passed to the reducer
    if current_word == word:
        current_count += count
    else:
        if current_word:
            # write result to STDOUT
            print ('%s\t%s' % (current_word, current_count))
        current_count = count
        current_word = word

# do not forget to output the last word if needed!
if current_word == word:
    print ('%s\t%s' % (current_word, current_count))